// Code generated by ogen, DO NOT EDIT.

package nhentaiapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetBookOperation               OperationName = "GetBook"
	GetPageCoverImageOperation     OperationName = "GetPageCoverImage"
	GetPageImageOperation          OperationName = "GetPageImage"
	GetPageThumbnailImageOperation OperationName = "GetPageThumbnailImage"
	RelatedOperation               OperationName = "Related"
	SearchOperation                OperationName = "Search"
	SearchByTagIDOperation         OperationName = "SearchByTagID"
)
